name: sample-workflow
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: sphinxdoc/sphinx-latexpdf
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: 3.13t

      - name: Setup plantuml
        run: |-
          apt update
          apt install wget openjdk-17-jre-headless fonts-noto-cjk
          wget -O /usr/local/bin/plantuml.jar https://github.com/plantuml/plantuml/releases/download/v1.2026.2/plantuml-mit-1.2026.2.jar
          echo skinparam defaultFontName \"Noto Sans CJK JP\" > /usr/local/share/jp.pu
          echo skinparam dpi 100 >> /usr/local/share/jp.pu
      
      - name: Build sphinx
        run: uv run sphinx-build source/ doc/
      
      - name: Build sphinx-pdf
        run: uv run sphinx-build -M latexpdfja source/ pdf/

      - name: Move pdf into HTML dir
        run: cp pdf/latex/*.pdf doc/test.pdf
      
      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc/
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to github pages
        uses: actions/deploy-pages@v4
        id: deployment