name: sample-workflow
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: 3.13t
      
      - name: Build sphinx
        run: uv run sphinx-build source/ doc/
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public